"""
Notification Model

Stores per-user notifications generated by backend events
(new assignment, drive shortlist, mentorship request, etc.).

Notification types (string enum):
  assignment    — new assignment posted
  grade         — grade published
  attendance    — attendance warning (<75%)
  placement     — shortlisted / offer issued
  mentorship    — request accepted/declined
  announcement  — new college announcement
  chat          — new message in a conversation
  general       — miscellaneous
"""

import uuid
from datetime import datetime, timezone
from app.extensions import db


class Notification(db.Model):
    __tablename__ = "notifications"

    id          = db.Column(db.UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id     = db.Column(db.UUID(as_uuid=True), db.ForeignKey("users.id"),
                             nullable=False, index=True)
    title       = db.Column(db.String(255), nullable=False)
    body        = db.Column(db.Text,        nullable=True)
    notif_type  = db.Column(db.String(50),  nullable=False, default="general")
    # Optional link — e.g. "/drives/uuid" so the bell item is clickable
    link        = db.Column(db.String(500), nullable=True)
    is_read     = db.Column(db.Boolean,     default=False, nullable=False)
    created_at  = db.Column(db.DateTime,
                             default=lambda: datetime.now(timezone.utc))

    user = db.relationship("User", foreign_keys=[user_id])

    def to_dict(self):
        return {
            "id":         str(self.id),
            "title":      self.title,
            "text":       self.body,
            "type":       self.notif_type,
            "link":       self.link,
            "unread":     not self.is_read,
            "time":       self.created_at.strftime("%b %d · %I:%M %p") if self.created_at else "",
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
