"""add branch_placements table

Revision ID: dbcb9dee9e8a
Revises: d4e5f6a7b8c9
Create Date: 2026-07-10 19:59:58.994863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcb9dee9e8a'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_placements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('placed_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch_placements')
    # ### end Alembic commands ###
